### ISSUE TITLE
Large Sign | Issue with Valheim Patch v0.214.2

### ISSUE THREAD

**Issue by ValhallaCommunity** [plumga/Clutter#6]
Hi Plumga,

With the recent valheim patch, I think the large sign might have broke.

![image](https://user-images.githubusercontent.com/124803112/225165773-a0e8ee9b-ec26-4f8f-ae6c-ad9862fe4a3a.png)

Thank you!

**Comment by plumga** [comment]
working on the fix, thanks for the report!

**Comment by plumga** [comment]
fixed in V0.1.4
