### ISSUE TITLE
Clutter Mod not working anymore after path 0.216.9

### ISSUE THREAD

**Issue by LittyLogged** [plumga/Clutter#8]
Seems that Jotuun Item Manager fails to load the clutter items (At least for me)

**Comment by AzumattDev** [comment]
Seems to be working fine for me.

**Comment by ValhallaCommunity** [comment]
FWIW, I haven't had any issues yet with Clutter.

I have with Distant Dynasties. Do you have a log file @LittyLogged

**Comment by LittyLogged** [comment]
Sorry, I meant to put that my issue is a result of running Agua and Any OdinPlus Mod (after patch 0.216.9)

**Comment by LittyLogged** [comment]
Auga - RandyKnapp*

**Comment by plumga** [comment]
Hi :D 
looks like y'all have things handled (thank you!) but just came to add that I just tested too and seems to be working fine on its own. 
Did you reach out to RandyKnapp?

**Comment by LittyLogged** [comment]
The issue has been resolved after Jotuun updated.
